#!/usr/bin/env python3
"""
Generate paste/<page>.md paste boards from blocks/<page>/*.html fragments.

A paste board is a single scrollable page for Shannon to work from in GHL:
each fragment's HTML in the order it goes on the page, with every
GHL NATIVE placeholder pulled out into a blockquote right after the
fragment that contains it, so the "what native element goes here" note
doesn't get lost inside a wall of markup.

Run: python3 scripts/build-paste-boards.py
Regenerate any time a file under blocks/ changes — paste/ is generated
output, never hand-edited.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BLOCKS = ROOT / "blocks"
PASTE = ROOT / "paste"

PAGES = {
    "home": {
        "title": "Home",
        "slug": "/",
        "title_tag": "Business Psychology for Owners of Growing Companies | Syncovate",
        "meta_description": "Dr. Shannon Jennings, business psychologist, works with owners of growing trades, manufacturing, and family businesses. Leadership advisory and team facilitation.",
        "jsonld": "Site-wide block only (no page-specific block needed).",
    },
    "how-i-work": {
        "title": "How I Work",
        "slug": "/how-i-work",
        "title_tag": "Leadership Advisory, Team Facilitation & Retreats | Syncovate",
        "meta_description": "Work with Dr. J one-on-one or bring her in for your team — leadership workshops, retreats, and strategy sessions for owners of growing companies. Starts at $1,500.",
        "jsonld": "Site-wide block + HOW I WORK PAGE ONLY block from assets/02-schema-jsonld.html.",
    },
    "writing": {
        "title": "Writing",
        "slug": "/writing",
        "title_tag": "Through the Prism: Leadership & Business Psychology Field Notes | Syncovate",
        "meta_description": "Short field notes on leadership, growing companies, and the psychology of running a business — plus the Saturday Seed: one idea you can put into play Monday.",
        "jsonld": "Site-wide block + WRITING PAGE ONLY block from assets/02-schema-jsonld.html.",
    },
    "about": {
        "title": "About",
        "slug": "/about",
        "title_tag": "About Dr. Shannon Jennings, Business Psychologist | Syncovate",
        "meta_description": "Dr. Shannon Jennings (Dr. J) holds a doctorate in business psychology and 20 years of experience with entrepreneurs, family businesses, and leadership teams.",
        "jsonld": "Site-wide block + ABOUT PAGE ONLY block from assets/02-schema-jsonld.html.",
    },
    "contact": {
        "title": "Contact",
        "slug": "/contact",
        "title_tag": "Contact Dr. J — Leadership Advisor, South Bend & Elkhart | Syncovate",
        "meta_description": "Start with a 15-minute call with Dr. Shannon Jennings. No pitch, no pressure. Or call, text, or email directly.",
        "jsonld": "Site-wide block + CONTACT PAGE ONLY block from assets/02-schema-jsonld.html.",
    },
}

NATIVE_RE = re.compile(r"<!--\s*(GHL NATIVE:.*?)-->", re.DOTALL)


def native_notes(html: str):
    notes = []
    for match in NATIVE_RE.finditer(html):
        lines = [ln.strip() for ln in match.group(1).strip().splitlines()]
        notes.append(" ".join(lines).strip())
    return notes


def build_page(page_key: str, meta: dict) -> str:
    page_dir = BLOCKS / page_key
    fragments = sorted(page_dir.glob("*.html"))

    out = [
        f"# {meta['title']} — Paste Board (`{meta['slug']}`)",
        "",
        "> Auto-generated by `scripts/build-paste-boards.py` from `blocks/"
        f"{page_key}/`. Do not hand-edit — regenerate instead.",
        "",
        f"**Title tag:** {meta['title_tag']}",
        "",
        f"**Meta description:** {meta['meta_description']}",
        "",
        f"**JSON-LD:** {meta['jsonld']}",
        "",
        "---",
        "",
    ]

    for i, fragment in enumerate(fragments, start=1):
        html = fragment.read_text()
        out.append(f"## {i}. `{fragment.name}`")
        out.append("")
        out.append("```html")
        out.append(html.rstrip("\n"))
        out.append("```")
        out.append("")

        for note in native_notes(html):
            out.append(f"> {note}")
            out.append(">")
        if native_notes(html):
            out.pop()  # drop trailing blank blockquote line
            out.append("")

        out.append("---")
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def main():
    PASTE.mkdir(exist_ok=True)
    for page_key, meta in PAGES.items():
        content = build_page(page_key, meta)
        out_path = PASTE / f"{page_key}.md"
        out_path.write_text(content)
        print(f"wrote {out_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
